### ISSUE TITLE
When will it be open source?

### ISSUE THREAD

**Issue by chengm0-0** [tyuezhan/SEER#1]
Congratulations on your perfect job being accepted by ICRA 2023! I would like to know when you will open source the code? Thanks :)

**Comment by VinMing** [comment]
已收到。

**Comment by tyuezhan** [comment]
Thank you for showing interests of our code! We plan to have the first release version by the end of this month. Please stay tuned!

**Comment by chengm0-0** [comment]
Thank you for your reply!
